queue:
  name: Hosted Ubuntu 1604


variables:
  - group: 'Terraform Service Principal'
  - group: 'Terraform State'
  - name: tfstate_key
    value: 'jimpaine.emotion-checker.master.tfstate'
  - name: resource_name
    value: 'emotionchecker'
  
steps:

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in **/*.tfvars'

  inputs:
    rootDirectory: ./env
    targetFiles: '**/*.tfvars'

- script: |
   terraform init \
       -backend-config="resource_group_name=$(tfstate_resource_group)" \
       -backend-config="storage_account_name=$(tfstate_storage_account)" \
       -backend-config="container_name=$(tfstate_container)" \
       -backend-config="key=$(tfstate_key)" \
       -backend-config="access_key=$(tfstate_access_key)"

  workingDirectory: ./env
  displayName: 'Terraform init'

- script: |
   terraform apply -auto-approve

  workingDirectory: ./env
  displayName: 'Terraform apply'

- task: DotNetCoreCLI@2
  displayName: 'Build Function'
  inputs:
    command: publish
    publishWebProjects: false
    projects: './src/ImageProcessor/ImageProcessor.csproj'
    arguments: '--configuration Release --output $(build.artifactstagingdirectory)'    
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- bash: |
   connectionstring=$(terraform output -json primary_connection_string | jq '.value' | tr -d '"')   
   fileendpoint=$(terraform output -json file_endpoint | jq '.value' | tr -d '"')   
   functionname=$(terraform output -json function_name | jq '.value' | tr -d '"')   
   resourcegroup=$(terraform output -json resource_group | jq '.value' | tr -d '"')
   
   az login \
        --service-principal \
        -u $(app_url) \
        -p $(client_secret) \
        --tenant $(tenant_id)

   az functionapp stop \
       --name $functionname \
       --resource-group $resourcegroup
   
   az storage file delete-batch \
       --source "$fileendpoint$functionname-content" \
       --connection-string $connectionstring
   
   az storage file upload-batch \
       --destination "$fileendpoint$functionname-content" \
       --source $(build.artifactstagingdirectory) \
       --destination-path "site/wwwroot" \
       --connection-string $connectionstring

   az functionapp start \
       --name $functionname \
       --resource-group $resourcegroup 

  workingDirectory: ./env
  displayName: Publish
